export default {
    zh: [
        { name: '简体中文', key: 'zh' },
        { name: '繁体中文', key: 'cht' },
        { name: '英语', key: 'en' },
        { name: '粤语', key: 'yue' },
        { name: '文言文', key: 'wyw' },
        { name: '日语', key: 'jp' },
        { name: '韩语', key: 'kor' },
        { name: '法语', key: 'fra' },
        { name: '西班牙语', key: 'spa' },
        { name: '泰语', key: 'th' },
        { name: '阿拉伯语', key: 'ara' },
        { name: '俄语', key: 'ru' },
        { name: '葡萄牙语', key: 'pt' },
        { name: '德语', key: 'de' },
        { name: '意大利语', key: 'it' },
        { name: '希腊语', key: 'el' },
        { name: '荷兰语', key: 'nl' },
        { name: '波兰语', key: 'pl' },
        { name: '保加利亚语', key: 'bul' },
        { name: '爱沙尼亚语', key: 'est' },
        { name: '丹麦语', key: 'dan' },
        { name: '芬兰语', key: 'fin' },
        { name: '捷克语', key: 'cs' },
        { name: '罗马尼亚语', key: 'rom' },
        { name: '斯洛文尼亚语', key: 'slo' },
        { name: '瑞典语', key: 'swe' },
        { name: '匈牙利语', key: 'hu' },
        { name: '越南语', key: 'vie' },
    ],
    en: [
        { name: 'Chinese Simplified', key: 'zh' },
        { name: 'Chinese Traditional', key: 'cht' },
        { name: 'English', key: 'en' },
        { name: 'Cantonese', key: 'yue' },
        { name: 'Classical Chinese', key: 'wyw' },
        { name: 'Japanese', key: 'jp' },
        { name: 'Korean', key: 'kor' },
        { name: 'French', key: 'fra' },
        { name: 'Spanish', key: 'spa' },
        { name: 'Thai', key: 'th' },
        { name: 'Arabic', key: 'ara' },
        { name: 'Russian', key: 'ru' },
        { name: 'Portuguese', key: 'pt' },
        { name: 'German', key: 'de' },
        { name: 'Italian', key: 'it' },
        { name: 'Greek', key: 'el' },
        { name: 'Dutch', key: 'nl' },
        { name: 'Polish', key: 'pl' },
        { name: 'Bulgarian', key: 'bul' },
        { name: 'Estonian', key: 'est' },
        { name: 'Danish', key: 'dan' },
        { name: 'Finnish', key: 'fin' },
        { name: 'Czech', key: 'cs' },
        { name: 'Romanian', key: 'rom' },
        { name: 'Slovenian', key: 'slo' },
        { name: 'Swedish', key: 'swe' },
        { name: 'Hungarian', key: 'hu' },
        { name: 'Vietnamese', key: 'vie' },
    ],
};
